local f = io.open('msha3ka.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 msha3ka.sh')
os.execute('killall -9 tg')
os.execute('rm -rf msha3ka.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('msha3ka.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 msha3ka.sh')
os.execute('screen ./msha3ka.sh')
